### DISCUSSION TITLE
Migrated from Wordpress to Hugo: PushEVs

### DISCUSSION THREAD

**Discussion by LITUATUI** [hbstack/theme-cards#227] [Show and tell]
I finally migrated my website from Wordpress to Hugo. I think it'll be a good showcase for this theme.

Now I'm trying to understand why disqus isn't working. Already enable it in [hugo.yaml](https://github.com/LITUATUI/pushevs.com/blob/main/config/production/hugo.yaml) and in [module.yaml](https://github.com/LITUATUI/pushevs.com/blob/main/config/_default/module.yaml).

[PushEVs](https://pushevs.com/)

**Comment by razonyang** [comment]
Seems the configuration is out-of-date, https://gohugo.io/templates/embedded/#configure-disqus.

Does the following configuration work?

```yaml
// hugo.yaml
services:
  disqus:
    shortname: your-disqus-shortname
```
