### DISCUSSION TITLE
Disable TOC and breadcrumb

### DISCUSSION THREAD

**Discussion by LITUATUI** [hbstack/theme-cards#230] [Q&A] [answered]
What's the recommended way of disable TOC and breadcrumb for the entire website?

Couldn't find it in the docs.

They are nice for documentation, but not for a blog.

**Comment by razonyang** [comment, marked as answer]
There is a `toc` page parameter, set it as `false` to disable the ToC, configure it with [cascade](https://gohugo.io/content-management/front-matter/#cascade) would simplify this setup.

```yaml
// hugo.yaml
cascade:
- _target:
    kind: page
  params:
    toc: false
```

For example, the config above setting the `toc` parameter as `false` for all detailed pages, tweak it to suit your needs.
