### DISCUSSION TITLE
Configure some menu entries to open in a new tab

### DISCUSSION THREAD

**Discussion by LITUATUI** [hbstack/theme-cards#258] [Q&A] [answered]
Is there a way to configure some menu entries to open in a new tab?

I have redirected URLs that look like internal links, but are actually externals - that I want to open in a new tab.

For example, the partners and stores sections of my [website](https://pushevs.com/).

**Comment by razonyang** [comment, marked as answer]
There is a `target` parameter for menu entry, probably undocumented.

```yaml
main:
  - name: Foo
    params:
      target: _blank
```
