### DISCUSSION TITLE
Option to remove header banner bottom margim

### DISCUSSION THREAD

**Discussion by LITUATUI** [hbstack/theme-cards#648] [Q&A] [answered]
This [module](https://hbstack.dev/modules/header/banner/) is great for landing pages, but we should have an option to hide the bottom margin. It looks good in light themes, but on dark themes the bottom margin is an ugly dark grey bar with no use, unless you use a transparent image.

![Header_banner_bottom_margin_light](https://github.com/user-attachments/assets/b751d592-1942-4535-b731-3a80e1a08a8f)
![Header_banner_bottom_margin_dark](https://github.com/user-attachments/assets/9cab9a0d-7a29-467d-96ab-732f88c6e8c4)

@razonyang could you introduce an option to remove that dark grey bar between the header banner and the footer?

Thanks.

**Comment by razonyang** [comment, marked as answer]
It's not an universal case, so it won't happen in this module, but there is a custom solution, to do this, put the following custom SCSS into your site.

```scss
[data-bs-theme="dark"] {
  [data-layout="landing"] {
    .hb-header,
    .hb-main {
      margin-bottom: 0 !important;
    }
  }
}
```
