### ISSUE TITLE
How to host theme-cards on cloudflare with such cloudflare-pages.yaml ?

### ISSUE THREAD

**Issue by techhubhub** [hbstack/theme-cards#140]
<img width="550" alt="image" src="https://github.com/hbstack/theme-cards/assets/158099291/be3e4b05-4356-490f-9d28-770be0dbfa50">

dev/exsite/.github/workflow
cat cloudflare-pages.yaml 

```
name: Cloudflare Pages

on:
  # auto deploy when pushing to specified branches.
  push:
    branches:
      - main

  # allow triggering workflow manually.
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-            

      - name: Install dependencies
        run: npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-            

      - name: Build
        run: hugo --minify --gc --enableGitInfo
        # Use following instead if defaultContentLanguageInSubdir is enabled.
        # run: hugo --minify --gc --enableGitInfo && cp public/en/404.html public/404.html

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: hb-theme
          directory: ./public
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

```

and CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID are filled
