### ISSUE TITLE
comment button

### ISSUE THREAD

**Issue by stardoom4** [hbstack/theme-cards#255]
I dont know if this is a bug or what but even after removing the comment module from module.yaml , the comment button shows under every post and a bootstrap card remains in the deployed site in the place of comments.

**Comment by razonyang** [comment]
Could you please provide a screenshot about this.

**Comment by stardoom4** [comment]
![Screenshot_2024-03-25-13-13-25-00_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hbstack/theme-cards/assets/139852159/faf454c1-16a3-462e-8d9e-fa97bd1d4a79)
Here is the screenshot.

**Comment by razonyang** [comment]
I see, that belongs the content panel module, to remove the comments button, you can pass `comments` parameter for all pages.

```yaml
// hugo.yaml
cascade:
  - _target:
      path: '*/**'
    params:
      comments: false
```

**Comment by stardoom4** [comment]
it did not work. it is still there.

**Comment by razonyang** [comment]
I've double check the codesnippet, it should work, there are some potential causes.

1. Typos
2. Wrong configuration file.
3. Dulplicate `cascade` configuration which will be overriden by others.

You can share your repo with me by Email if you can't figure it out.

**Comment by stardoom4** [comment]
```                                                                                             
baseURL: 
title: 
# Copyright, the {year} is the placeholder of this year.
copyright: "Public Domain."
defaultContentLanguage: en
defaultContentLanguageInSubdir: false # when true, append the default language code into URL, i.e. /docs -> /en/docs.
enableRobotsTXT: true
timeout: 120s
enableEmoji: true

title_sections: true # when false, remove the sections from the title.
title_sections_depth: 0 # the depth of sections on the title.
title_sections_depth_dir: end # when start, the depth is counting from the root sections.

permalinks:
  blog: /blog/:year/:month/:title
  news: /news/:year/:month/:title

cascade:
  - _target:
      path: '*/**'
    params:
      comments: false
  
outputs:
  home:
    - HTML
    - Offline        # required by PWA module for displaying the offline pages.
    - RSS
    - SearchIndex    # required by search module.
    - WebAppManifest # required by PWA module to make your site installable.

taxonomies:
  authors: authors       # multiple authors.
  tags: tags
  categories: categories
  series: series

build:
  writeStats: true # required by PurgeCSS.

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    lineNos: true
    lineNumbersInTable: false

# see https://gohugo.io/content-management/related/#configure-related-content
related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 80
  - name: categories
    weight: 60
  - name: series
    weight: 60
  - name: authors
    weight: 10
  - name: date
    weight: 10
  threshold: 10 # for testing, increase it to suit your case.
  toLower: false
    
security:
  funcs:
    getenv:
      - ^HUGO
      - CI$
      - PWD
```
here is my hugo.yaml file.

**Comment by razonyang** [comment]
Nothing I can help, too limited information to debug, as the GIF shown below, the code snippet is correct.

![peek_1](https://github.com/hbstack/theme-cards/assets/17720932/7da0dca5-6d04-4546-ad3d-cd6a922fbfd0)

There are some hints.

1. Global search `cascade` make sure there isn't duplicated configuration.
2. Update all modules via `hugo mod get -u`.
3. Upgrade to latest Hugo version.
4. `CTRL` + `F5` to force refresh page or clear browser caches and then refresh page.

If still not working, please provide a minimal reproducible repo (copy repo and delete any sensetive content).

**Comment by stardoom4** [comment]
Okay , I will update the repo.

**Comment by razonyang** [comment]
There is a workaround, setting `hb.content_panel.comments` as `false`, please note that this approach will disable comments for all of pages.

Firstly, upgrade to latest version of content panel.

```sh
hugo mod get github.com/hbstack/content-panel@v0.8.0
```

And then configure the parameter as follows.

```yaml
// params.yaml
hb:
  content_panel:
    comments: false
```
I'm closing this issue now, please feel free to reopen or open another issue if this not resolved.
